version: "2"

services:
  admin:
    build:
      context: .
      dockerfile: ./apps/admin/Dockerfile
      target: development
    command: npm run dev admin
    env_file:
      - ./apps/admin/.env
    ports:
      - '5000:5000'
    volumes:
      - .:/usr/src/app
  order:
    build:
      context: .
      dockerfile: ./apps/order/Dockerfile
      target: development
    command: npm run dev order
    env_file:
      - ./apps/order/.env
    ports:
      - '5001:5001'
    volumes:
      - .:/usr/src/app

  rabbitmq:
    image: rabbitmq
    ports:
     - 5672:5672